name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure Dependencies
      # Install dependencies
      run: sudo apt-add-repository universe && sudo apt update && sudo apt install libfmt-dev -y

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Time Task
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: echo -e "23 59 59 0   0   0 1000" | ./1_time_task/time_task
      
    - name: String Task
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: echo -e "2051116001  Shakespeare doctor\n2051116002  hard\n2051116003" | ./2_string_task/string_task
      
    - name: Boxes Task
      working-directory: ${{github.workspace}}/build
      run: ./3_boxes_task/boxes_task
      
    - name: Dice Task - Part A
      working-directory: ${{github.workspace}}/build
      run: ./4_dice_task/partA
      
    - name: Dice Task - Part B
      working-directory: ${{github.workspace}}/build
      run: ./4_dice_task/partB  

    - name: Dice Task - Part C
      working-directory: ${{github.workspace}}/build
      run: ./4_dice_task/partC
      
    - name: Dice Task - Part D
      working-directory: ${{github.workspace}}/build
      run: ./4_dice_task/partD
